### ISSUE TITLE
Is the to() and wideTo() function supported?

### ISSUE THREAD

**Issue by Jayclifford345** [metrico/fluXpipe#19]
We are currently testing the ability to write data back to InfluxDB. 
```
 import "contrib/qxip/iox"
 import "influxdata/influxdb"
 iox.from(
     bucket: "quix",
     host: "eu-central-1-1.aws.cloud2.influxdata.com:443",
     token: "",
     limit: "10",
     table: "machine_data",
     start: -2d,
 )
 |> range(start: -2d)
 |> aggregateWindow(every: 5s, fn: mean, column: "load", createEmpty: false)
 |> set(key: "_measurement", value: "downsampled")
 |> wideTo(
     bucket: "quix",
     host: "https://eu-central-1-1.aws.cloud2.influxdata.com",
     token: "",
     orgID: "6a841c0c08328fb1"
    )

```

Is this currently possible? This would be a great feature for task-based downsampling/enrichment.

**Comment by lmangani** [comment]
Great point! Right now we only have a `from` wrapper for iox but I think this is a great next task for the "contrib/qxip/iox" roadmap and hopefully since its all in flux it should be as simple as extending the [flux wrapper](https://github.com/InfluxCommunity/flux/blob/master/stdlib/contrib/qxip/iox/iox.flux) around the iox.sql function to support inserts. Shall we transfer this into the InfluxCommunity/Flux repo?

**Comment by Jayclifford345** [comment]
This sounds good to me!

**Comment by lmangani** [comment]
@Jayclifford345 the other flightsql clients from influxdb all seem to use the line protocol API for inserts and none of them seem to be promoting SQL inserts much. Should this apply for the Flux client as well?

**Comment by Jayclifford345** [comment]
Hi @lmangani, sorry I misread your last message. Correct we currently do not support SQL INTO statements. It's purely a write line protocol via the write API. I belive the remote to() function should work as expected as this would simply write the query result to a remote data source. We might be able to leverage that code.

**Comment by lmangani** [comment]
In this case the standard `experimental.to` or `influx.wideTo` should work for writing as long as the required columns are there? If that works, I'm happy to wrap those into the iox contrib to make it as transparent as possible.

**Comment by lmangani** [comment]
After some analysis, it seems most of the old influx push functions depend on to the `Provider` component which we're exiting in Flux Community and Fluxpipe. I might be able to mock it but regardless the changes required to port the existing code into the new contrib unbundled should be quite reasonable considering the formats are all unchanged.

**Comment by akvlad** [comment]
hello @Jayclifford345 
I have managed to copy some of the data on my local iox instance with the next script:
```
import "influxdata/influxdb"
import "array"
import "sql"

sql.from(
        driverName: "influxdb-iox",
        dataSourceName: "iox://localhost:8082/test_test",
        query: "select * from logs_v2 limit 200;",
)   |> rename(columns: {"time":"_time"})
    |> set(key: "_measurement", value: "logsv4")
    |> group(columns: ["_measurement", "fingerprint"])
    |> influxdb.wideTo(
        bucket: "test",
        org: "test",
        token: "",
        host: "http://localhost:8080",
)
```
Is there any objections or concerns about this type of usage? This should works with the current fluXpipe version.

**Comment by lmangani** [comment]
@Jayclifford345 considering the above, we're rebuilding the public fluxpipe to allow the former influx dependencies and we should be good to go with all the existing inserting features

**Comment by lmangani** [comment]
good morning @Jayclifford345 a new version is coming with full support for writing to influxdb - stay tuned!

**Comment by lmangani** [comment]
@Jayclifford345 we should have full support for writing in FluxPipe v1.0.0 could you give it a try and confirm it meets your expectations? Thanks @akvlad for restoring the missing parts! 🥳

**Comment by lmangani** [comment]
Closing as resolved
